obj-y	+= main.o
obj-y	+= convert.o
obj-y	+= io.o
obj-y	+= fdset.o
obj-y	+= string.o
obj-y	+= context.o
obj-y	+= image.o
obj-y	+= protobuf.o
obj-y	+= obj.o
obj-y	+= read.o
obj-y	+= ns.o
obj-y	+= task.o
obj-y	+= net.o
obj-y	+= files.o

cflags-y += -iquote include

ifneq ($(MAKECMDGOALS),clean)
incdeps := y
endif
